service: slack-commands

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}

package:
  exclude:
    - credentials.sh
    - LICENSE
    - README.md

functions:
  # Private Mentions
  privateMentionsOnInstall:
    handler: privatementions.onInstall
    events:
      - http:
          path: private-mentions
          method: post
  privateMentionsOnChannel:
    handler: privatementions.onChannelCommand
    role: readOnlyLambdaRole
    events:
      - http:
          path: private-mentions/channel
          method: post
  privateMentionsOnHere:
    handler: privatementions.onHereCommand
    role: readOnlyLambdaRole
    events:
      - http:
          path: private-mentions/here
          method: post

resources:
  Resources:
    slackAuth:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SlackCommands
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 10
    readOnlyLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /my/default/path/
        RoleName: SlackCommands-ReadOnlyLambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: slackCommandsTableGetItem
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - "dynamodb:GetItem"
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:dynamodb'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'table/SlackCommands'
